stages:
  - build
  - test
  - deploy

variables:
  MAVEN_CLI_OPTS: "-s .deploy/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

include:
  - project: 'ucsdlibrary/development/gitlab-ci-tools'
    ref: master
    file: 'gitlab-ci-base.yml'
  - project: 'ucsdlibrary/development/gitlab-ci-tools'
    ref: master
    file: 'gitlab-ci-kaniko-build.yml'
  - project: 'ucsdlibrary/development/gitlab-ci-tools'
    ref: master
    file: 'gitlab-ci-helm-deploy.yml'

cache:
  paths:
    - .m2/repository/
    - target/

build_app:
  stage: build
  image: maven:3-jdk-8
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  image: maven:3-jdk-8
  script:
    - mvn $MAVEN_CLI_OPTS test

deploy:
  stage: deploy
  image: maven:3-jdk-8
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - master
